#%RAML 1.0 NamedExample
value: |
  {
    "customerId" : "google-oauth2",
    "status": "Draft",
    "orderItems": [
      {
        "orderItemId": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
        "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
        "location" : {
          "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
          "locationType": "STORE",
          "deliveryMethod": "PICKUP"
        },
        "price": "40", 
        "productName": "Supersonic Electronic",
        "quantity": 4
      },
      {
        "orderItemId": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
        "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
        "location" : {
          "locationId": "7307024a-7e63-11e7-bb31-be2e44b06b34",
          "locationType": "WAREHOUSE",
          "deliveryMethod": "SHIPMENT"
        },
        "price": "40", 
        "productName": "Supersonic Electronic",
        "quantity": 1
      },
      {
        "orderItemId": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
        "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
        "location" : {
          "locationId": "84c95f82-c435-4de0-8964-82e16bd23689",
          "locationType": "PARTNER",
          "deliveryMethod": "SHIPMENT"
        },
        "price": "40", 
        "productName": "Supersonic Electronic",
        "quantity": 4
      }
     ]  
    }