#%RAML 1.0
version: v2.0
title: Retail Order Fulfilment Process API
baseUri: http://localhost:8081/api

uses: 
  order: /exchange_modules/org.mule.templates/retail-order-types/1.0.2/retail_order_types.raml
  common: /exchange_modules/org.mule.templates/retail-common/1.0.1/retail_common.raml
  payment: /exchange_modules/org.mule.templates/retail-payment/1.0.2/retail_payment.raml

types:
  OrderRequest:
    type: object
    properties:
      status: order.Status
      customerId: common.ResourceId
      orderItems: order.OrderItemSummary[]

  OrderResponse: 
    type: object
    properties:
      status: 
        type: string
        description: Status of order
      identifier: common.ResourceId
      message: 
        type: string
        description: Information about order
       
/orders:
  post:
    displayName: Create order
    body: 
      application/json: 
        type: OrderRequest
        example: !include examples/orders-request.yaml
    responses:
      201: 
        body: 
          application/json:
            type: OrderResponse 
            example: !include examples/orders-response.yaml
  /{salesOrderId}:
    put:
      displayName: Update order
      responses:
        200:
          body:
            application/json: 
              type: payment.PaymentResponse
              example: !include examples/update-order-response.yaml